name: Deploy MkDocs

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v3
    - name: Install MkDocs
      run: pip3 install -r requirements.txt
    - name: Build docs
      run: mkdocs build
    # https://github.com/marketplace/actions/deploy-to-github-pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: site